export type Region = {
  id: number;
  name: string;
  lat: number;
  lon: number;
};

export const uzbekistanRegions: Region[] = [
  { id: 1, name: "Tashkent City", lat: 41.26465, lon: 69.21627 },
  { id: 2, name: "Andijan Region", lat: 40.76859, lon: 72.23638 },
  { id: 3, name: "Bukhara Region", lat: 40.25042, lon: 63.20322 },
  { id: 4, name: "Ferghana Region", lat: 40.45681, lon: 71.28742 },
  { id: 5, name: "Jizzakh Region", lat: 40.47064, lon: 67.57085 },
  { id: 6, name: "Namangan Region", lat: 41.051, lon: 71.09732 },
  { id: 7, name: "Navoiy Region", lat: 42.69886, lon: 64.63377 },
  { id: 8, name: "Qashqadaryo Region", lat: 38.89862, lon: 66.04635 },
  { id: 9, name: "Samarkand Region", lat: 39.62701, lon: 66.97497 },
  { id: 10, name: "Sirdaryo Region", lat: 40.38638, lon: 68.7155 },
  { id: 11, name: "Surxondaryo Region", lat: 37.9409, lon: 67.57085 },
  { id: 12, name: "Tashkent Region", lat: 41.22132, lon: 69.85974 },
  { id: 13, name: "Khorezm Region", lat: 41.35653, lon: 60.85667 },
  { id: 14, name: "Republic of Karakalpakstan", lat: 43.80413, lon: 59.4458 },
];

export type UzPlace = {
  district: string;
  region_name: string;
  region_type: string; // "region" | "republic" | "city"
  latitude: number;
  longitude: number;
};

export const uzbekistanDistricts: UzPlace[] = [
  {
    district: "Tashkent City",
    region_name: "Tashkent City",
    region_type: "city",
    latitude: 41.26465,
    longitude: 69.21627,
  },
  // --- Samarqand Region (region) ---
  {
    district: "Bulungʻur",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.7573,
    longitude: 67.2729,
  },
  {
    district: "Ishtixon",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.9664,
    longitude: 66.4861,
  },
  {
    district: "Jomboy",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.6989,
    longitude: 67.0933,
  },
  {
    district: "Kattaqoʻrgʻon",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.8989,
    longitude: 66.2561,
  },
  {
    district: "Qoʻshrabot",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 40.3333,
    longitude: 66.5,
  },
  {
    district: "Narpay",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.92,
    longitude: 65.9253,
  },
  {
    district: "Nurobod",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.2,
    longitude: 66.989,
  },
  {
    district: "Oqdaryo",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.7639,
    longitude: 66.9125,
  },
  {
    district: "Paxtachi",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.8,
    longitude: 66.9,
  },
  {
    district: "Payariq",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.57,
    longitude: 66.98,
  },
  {
    district: "Pastdargʻom",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.7161,
    longitude: 66.6642,
  },
  {
    district: "Samarqand",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.6542,
    longitude: 66.9597,
  },
  {
    district: "Toyloq",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.69,
    longitude: 67.09,
  },
  {
    district: "Urgut",
    region_name: "Samarqand",
    region_type: "region",
    latitude: 39.4022,
    longitude: 67.2431,
  },

  // --- Fergana Region (region) ---
  {
    district: "Oltiariq",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.3919,
    longitude: 71.4742,
  },
  {
    district: "Bagʻdod",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.37,
    longitude: 71.81,
  },
  {
    district: "Beshariq",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.335,
    longitude: 71.65,
  },
  {
    district: "Buvayda",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.33,
    longitude: 71.73,
  },
  {
    district: "Dangʻara",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.34,
    longitude: 71.91,
  },
  {
    district: "Fergana",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.47,
    longitude: 71.78,
  },
  {
    district: "Furqat",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.36,
    longitude: 71.54,
  },
  {
    district: "Qoʻshtepa",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.46,
    longitude: 71.95,
  },
  {
    district: "Quva",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.52,
    longitude: 72.07,
  },
  {
    district: "Rishton",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.3567,
    longitude: 71.2833,
  },
  {
    district: "Soʻx",
    region_name: "Fergana",
    region_type: "region",
    latitude: 39.6,
    longitude: 71.9,
  },
  {
    district: "Toshloq",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.46,
    longitude: 71.84,
  },
  {
    district: "Uchkoʻprik",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.107,
    longitude: 71.58,
  },
  {
    district: "Yozyovon",
    region_name: "Fergana",
    region_type: "region",
    latitude: 40.26,
    longitude: 70.95,
  },

  // --- Namangan Region (region) ---
  {
    district: "Chortoq",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.0692,
    longitude: 71.8237,
  },
  {
    district: "Chust",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.0033,
    longitude: 71.2379,
  },
  {
    district: "Kosonsoy",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.2494,
    longitude: 71.5474,
  },
  {
    district: "Mingbuloq",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.02,
    longitude: 71.38,
  },
  {
    district: "Namangan",
    region_name: "Namangan",
    region_type: "region",
    latitude: 40.9162,
    longitude: 71.5782,
  },
  {
    district: "Norin",
    region_name: "Namangan",
    region_type: "region",
    latitude: 40.9167,
    longitude: 72.1167,
  },
  {
    district: "Pop",
    region_name: "Namangan",
    region_type: "region",
    latitude: 40.8736,
    longitude: 71.1089,
  },
  {
    district: "Toʻraqoʻrgʻon",
    region_name: "Namangan",
    region_type: "region",
    latitude: 40.9998,
    longitude: 71.5116,
  },
  {
    district: "Uchqoʻrgʻon",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.1137,
    longitude: 72.0792,
  },
  {
    district: "Uychi",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.0807,
    longitude: 71.9233,
  },
  {
    district: "Yangiqoʻrgʻon",
    region_name: "Namangan",
    region_type: "region",
    latitude: 41.1947,
    longitude: 71.7239,
  },

  // --- Tashkent Region (region) ---
  {
    district: "Bekobod",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 40.2208,
    longitude: 69.2697,
  },
  {
    district: "Boʻka",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 40.56,
    longitude: 69.3,
  },
  {
    district: "Chinoz",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.4583,
    longitude: 69.475,
  },
  {
    district: "Ohangaron",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 40.9069,
    longitude: 69.6383,
  },
  {
    district: "Parkent",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.2944,
    longitude: 69.6764,
  },
  {
    district: "Piskent",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 40.31,
    longitude: 69.67,
  },
  {
    district: "Quyichirchiq",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.24,
    longitude: 69.69,
  },
  {
    district: "Yangiyoʻl",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 40.1736,
    longitude: 69.2826,
  },
  {
    district: "Zangiota",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.352,
    longitude: 69.434,
  },
  {
    district: "Qibray",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.216,
    longitude: 69.369,
  },
  {
    district: "Chirchiq",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.4689,
    longitude: 69.5822,
  },
  {
    district: "Yuqorichirchiq",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.53,
    longitude: 69.6,
  },
  {
    district: "Tashkent",
    region_name: "Tashkent Region",
    region_type: "region",
    latitude: 41.2995,
    longitude: 69.2401,
  }, // rural territories

  // --- Bukhara Region (region) ---
  {
    district: "Bukhara",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.7747,
    longitude: 64.4286,
  },
  {
    district: "Gʻijduvon",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 40.1,
    longitude: 64.6833,
  },
  {
    district: "Gʻaznavon",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.8,
    longitude: 64.8633,
  },
  {
    district: "Kogon",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.7226,
    longitude: 64.5513,
  },
  {
    district: "Olot",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 40.15,
    longitude: 64.2,
  },
  {
    district: "Peshku",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.578,
    longitude: 64.797,
  },
  {
    district: "Qorakol",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.54,
    longitude: 64.46,
  },
  {
    district: "Romitan",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.8,
    longitude: 64.27,
  },
  {
    district: "Vobkent",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 40.0,
    longitude: 64.5167,
  },
  {
    district: "Beshkent",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.45,
    longitude: 64.32,
  },
  {
    district: "Khiwa",
    region_name: "Bukhara",
    region_type: "region",
    latitude: 39.79,
    longitude: 64.62,
  },

  // --- Jizzakh Region (region) ---
  {
    district: "Zomin",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 39.976,
    longitude: 67.93,
  },
  {
    district: "Zafarobod",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.22,
    longitude: 67.56,
  },
  {
    district: "Gʻallaorol",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.017,
    longitude: 67.6,
  },
  {
    district: "Doʻstlik",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.3,
    longitude: 68.0,
  },
  {
    district: "Bakhmal",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.89,
    longitude: 67.6,
  },
  {
    district: "Jizzakh",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.125,
    longitude: 67.88,
  },
  {
    district: "Mirzachoʻl",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.5,
    longitude: 67.65,
  },
  {
    district: "Arnasoy",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.21,
    longitude: 67.7,
  },
  {
    district: "Paxtakor",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.3167,
    longitude: 67.95,
  },
  {
    district: "Dashtobod",
    region_name: "Jizzakh",
    region_type: "region",
    latitude: 40.126,
    longitude: 68.494,
  },

  // --- Navoiy Region (region) ---
  {
    district: "Navoiy",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 40.0844,
    longitude: 65.3792,
  },
  {
    district: "Karmana",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 40.1167,
    longitude: 65.35,
  },
  {
    district: "Qiziltepa",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 40.03,
    longitude: 65.118,
  },
  {
    district: "Nurota",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 40.53,
    longitude: 65.26,
  },
  {
    district: "Tomdi",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 40.8,
    longitude: 65.13,
  },
  {
    district: "Zarafshon",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 41.5822,
    longitude: 64.205,
  },
  {
    district: "Uchquduq",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 42.6667,
    longitude: 63.9833,
  },
  {
    district: "Konimex",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 41.9,
    longitude: 64.233,
  },
  {
    district: "Qizilcha",
    region_name: "Navoiy",
    region_type: "region",
    latitude: 40.95,
    longitude: 64.76,
  },

  // --- Qashqadaryo Region (region) ---
  {
    district: "Qarshi",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.8606,
    longitude: 65.7899,
  },
  {
    district: "Shahrisabz",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 39.0578,
    longitude: 66.8344,
  },
  {
    district: "Kitob",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 39.1211,
    longitude: 66.8897,
  },
  {
    district: "Muborak",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 39.2553,
    longitude: 65.1528,
  },
  {
    district: "Yakkabogʻ",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.9628,
    longitude: 66.6581,
  },
  {
    district: "Kasbi",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.825,
    longitude: 65.823,
  },
  {
    district: "Koson",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.9,
    longitude: 65.95,
  },
  {
    district: "Nishon",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.7,
    longitude: 65.81,
  },
  {
    district: "Gʻuzor",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.2,
    longitude: 66.25,
  },
  {
    district: "Chiroqchi",
    region_name: "Qashqadaryo",
    region_type: "region",
    latitude: 38.3,
    longitude: 66.35,
  },

  // --- Sirdaryo Region (region) ---
  {
    district: "Gulistan",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.4897,
    longitude: 68.78,
  },
  {
    district: "Yangiyer",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.2758,
    longitude: 68.8222,
  },
  {
    district: "Shirin",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.2333,
    longitude: 68.6667,
  },
  {
    district: "Sirdaryo",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.843,
    longitude: 68.661,
  },
  {
    district: "Baxt",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.37,
    longitude: 68.146,
  },
  {
    district: "Hovos",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.43,
    longitude: 68.9,
  },
  {
    district: "Boyovut",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.58,
    longitude: 68.48,
  },
  {
    district: "Oqoltin",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.23,
    longitude: 68.4,
  },
  {
    district: "Mirzaobod",
    region_name: "Sirdaryo",
    region_type: "region",
    latitude: 40.63,
    longitude: 68.95,
  },

  // --- Surxondaryo Region (region) ---
  {
    district: "Termiz",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 37.2242,
    longitude: 67.2783,
  },
  {
    district: "Denov",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 38.267,
    longitude: 67.8989,
  },
  {
    district: "Boysun",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 38.2058,
    longitude: 67.1981,
  },
  {
    district: "Jarqoʻrgʻon",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 37.4947,
    longitude: 67.3972,
  },
  {
    district: "Sherobod",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 37.6792,
    longitude: 67.0067,
  },
  {
    district: "Qumqoʻrgʻon",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 37.75,
    longitude: 67.2,
  },
  {
    district: "Angor",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 38.0,
    longitude: 67.35,
  },
  {
    district: "Shoʻrchi",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 38.12,
    longitude: 67.28,
  },
  {
    district: "Sariosiyo",
    region_name: "Surxondaryo",
    region_type: "region",
    latitude: 37.5,
    longitude: 67.4,
  },

  // --- Xorazm Region (region) ---
  {
    district: "Urganch",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.55,
    longitude: 60.6333,
  },
  {
    district: "Xiva",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.379,
    longitude: 60.3633,
  },
  {
    district: "Shovot",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.6578,
    longitude: 60.2883,
  },
  {
    district: "Gurlan",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.8447,
    longitude: 60.3914,
  },
  {
    district: "Yangiarik",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.319,
    longitude: 60.605,
  },
  {
    district: "Qoʻshkoʻpir",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.66,
    longitude: 61.13,
  },
  {
    district: "Bogʻot",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.43,
    longitude: 60.53,
  },
  {
    district: "Hazorasp",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 42.1,
    longitude: 59.61,
  },
  {
    district: "Tuproqqalʼa",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 42.02,
    longitude: 59.9,
  },
  {
    district: "Khonqa",
    region_name: "Xorazm",
    region_type: "region",
    latitude: 41.73,
    longitude: 60.18,
  },

  // --- Karakalpakstan (republic) ---
  {
    district: "Nukus",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.4609,
    longitude: 59.6154,
  },
  {
    district: "Xojayli",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.4,
    longitude: 59.4667,
  },
  {
    district: "Toʻrtkoʻl",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 41.5481,
    longitude: 61.0006,
  },
  {
    district: "Kungrad",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 43.0833,
    longitude: 58.9,
  },
  {
    district: "Moʻynoq",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 44.5833,
    longitude: 58.9833,
  },
  {
    district: "Chimboy",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 41.96,
    longitude: 59.45,
  },
  {
    district: "Mangʻit",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.05,
    longitude: 59.42,
  },
  {
    district: "Beruniy",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.054,
    longitude: 59.211,
  },
  {
    district: "Qanlikoʻl",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.08,
    longitude: 60.0,
  },
  {
    district: "Kegeyli",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.65,
    longitude: 59.2,
  },
  {
    district: "Qorauzak",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 42.32,
    longitude: 59.35,
  },
  {
    district: "Taʼqiyatash",
    region_name: "Karakalpakstan",
    region_type: "republic",
    latitude: 41.87,
    longitude: 58.55,
  },
];
